/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StudentManagement;

import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.*;
import javax.swing.*;

/**
 *
 * @author Aktaruzzaman
 */
public class AddStudent extends javax.swing.JFrame {
    MainPage mainPage;
    private static Connection connection;
    boolean checkReadyForDatabese = false;
    boolean regComplete = false;
    /**
     * Creates new form AddStudent
     */
    public AddStudent() {
        initComponents();
        setResizable(false);
        this.setSize(1200, 700);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../images/titleBarIcon.png")));

        mainPage = new MainPage();
        MainPage.addPlaaceholderStytle(stdName);
        MainPage.addPlaaceholderStytle(stdId);
        MainPage.addPlaaceholderStytle(stdPhone);
        MainPage.addPlaaceholderStytle(stdGarName);
        MainPage.addPlaaceholderStytle(stdGarPhone);
        MainPage.addPlaaceholderStytle(stdAddress);
        MainPage.addPlaaceholderStytle(stdPassword);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        stdName = new javax.swing.JTextField();
        stdId = new javax.swing.JTextField();
        stdPhone = new javax.swing.JTextField();
        stdSem = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        stdYear = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        stdBirthDate = new javax.swing.JComboBox<>();
        stdBirthMonth = new javax.swing.JComboBox<>();
        stdBirthYear = new javax.swing.JComboBox<>();
        stdGender = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        stdDept = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        stdGarName = new javax.swing.JTextField();
        stdRelGurd = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        stdAddress = new javax.swing.JTextField();
        stdGarPhone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        stdPassword = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        logOutBtn = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        backBtn = new javax.swing.JLabel();
        stdIntake = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Student");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addStudentPage.png"))); // NOI18N

        stdName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdName.setForeground(new java.awt.Color(153, 153, 153));
        stdName.setText("  Student name");
        stdName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 91, 102)));
        stdName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stdNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stdNameFocusLost(evt);
            }
        });
        stdName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdNameActionPerformed(evt);
            }
        });

        stdId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdId.setForeground(new java.awt.Color(153, 153, 153));
        stdId.setText("  Student Id");
        stdId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 91, 102)));
        stdId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stdIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stdIdFocusLost(evt);
            }
        });
        stdId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdIdActionPerformed(evt);
            }
        });

        stdPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdPhone.setForeground(new java.awt.Color(153, 153, 153));
        stdPhone.setText("  Phone");
        stdPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 91, 102)));
        stdPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stdPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stdPhoneFocusLost(evt);
            }
        });
        stdPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdPhoneActionPerformed(evt);
            }
        });

        stdSem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdSem.setForeground(new java.awt.Color(255, 255, 255));
        stdSem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "Spring", "Fall" }));
        stdSem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 91, 102)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Semester");

        stdYear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdYear.setForeground(new java.awt.Color(255, 255, 255));
        stdYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "year", "2023", "2024", "2025", "2026", "2027" }));
        stdYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 91, 102)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Year");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Date of Birth");

        stdBirthDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdBirthDate.setForeground(new java.awt.Color(255, 255, 255));
        stdBirthDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        stdBirthDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 91, 102)));

        stdBirthMonth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdBirthMonth.setForeground(new java.awt.Color(255, 255, 255));
        stdBirthMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        stdBirthMonth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 91, 102)));

        stdBirthYear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdBirthYear.setForeground(new java.awt.Color(255, 255, 255));
        stdBirthYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "year", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980" }));
        stdBirthYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 91, 102)));

        stdGender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdGender.setForeground(new java.awt.Color(255, 255, 255));
        stdGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "Male", "Female" }));
        stdGender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 91, 102)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Gender");

        stdDept.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdDept.setForeground(new java.awt.Color(255, 255, 255));
        stdDept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "Computer Science and Engineering" }));
        stdDept.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 91, 102)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Department");

        stdGarName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdGarName.setForeground(new java.awt.Color(153, 153, 153));
        stdGarName.setText("  Gurdian name");
        stdGarName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 91, 102)));
        stdGarName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stdGarNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stdGarNameFocusLost(evt);
            }
        });
        stdGarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdGarNameActionPerformed(evt);
            }
        });

        stdRelGurd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdRelGurd.setForeground(new java.awt.Color(255, 255, 255));
        stdRelGurd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "Father", "Mother", "Brother", "Sister" }));
        stdRelGurd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 91, 102)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Relation with gurdian");

        stdAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdAddress.setForeground(new java.awt.Color(153, 153, 153));
        stdAddress.setText("  Address");
        stdAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 91, 102)));
        stdAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stdAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stdAddressFocusLost(evt);
            }
        });
        stdAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdAddressActionPerformed(evt);
            }
        });

        stdGarPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdGarPhone.setForeground(new java.awt.Color(153, 153, 153));
        stdGarPhone.setText("  Gurdian phone");
        stdGarPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 91, 102)));
        stdGarPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stdGarPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stdGarPhoneFocusLost(evt);
            }
        });
        stdGarPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdGarPhoneActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(241, 91, 102));
        jButton1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD STUDENT");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        stdPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdPassword.setForeground(new java.awt.Color(153, 153, 153));
        stdPassword.setText("  Student password");
        stdPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 91, 102)));
        stdPassword.setEchoChar('\u0000');
        stdPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stdPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stdPasswordFocusLost(evt);
            }
        });
        stdPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdPasswordActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(241, 91, 102));
        jPanel5.setPreferredSize(new java.awt.Dimension(115, 45));

        logOutBtn.setBackground(new java.awt.Color(0, 153, 204));
        logOutBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logOutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutBtn))
        );

        jPanel6.setBackground(new java.awt.Color(241, 91, 102));
        jPanel6.setPreferredSize(new java.awt.Dimension(115, 45));

        backBtn.setBackground(new java.awt.Color(0, 153, 204));
        backBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn))
        );

        stdIntake.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdIntake.setForeground(new java.awt.Color(255, 255, 255));
        stdIntake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "41", "42" }));
        stdIntake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 91, 102)));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Intake");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stdPhone)
                            .addComponent(stdSem, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stdDept, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stdPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stdId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(stdBirthDate, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(stdBirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(stdBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(stdYear, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(stdGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(stdGarPhone)
                                .addComponent(stdIntake, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(stdName, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6)
                                        .addComponent(stdAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addComponent(stdGarName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(stdRelGurd, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(62, 62, 62))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stdId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stdName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stdGender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(stdBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdBirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stdSem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stdYear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stdDept, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stdIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stdPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stdGarName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stdRelGurd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stdGarPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stdAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
          this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void stdNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdNameFocusGained
        if(stdName.getText().equals("  Student name")){
            stdName.setText(null);
            stdName.requestFocus();
            mainPage.removePlaaceholderStytle(stdName);
        }
    }//GEN-LAST:event_stdNameFocusGained

    private void stdNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdNameFocusLost
        // TODO add your handling code here:
        if(stdName.getText().length() == 0){
            MainPage.addPlaaceholderStytle(stdName);
            stdName.setText("  Student name");
        }
    }//GEN-LAST:event_stdNameFocusLost

    private void stdNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdNameActionPerformed

    }//GEN-LAST:event_stdNameActionPerformed

    private void stdIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdIdFocusGained
          if(stdId.getText().equals("  Student Id")){
            stdId.setText(null);
            stdId.requestFocus();
            mainPage.removePlaaceholderStytle(stdId);
        }
    }//GEN-LAST:event_stdIdFocusGained

    private void stdIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdIdFocusLost
        if(stdId.getText().length() == 0){
            MainPage.addPlaaceholderStytle(stdId);
            stdId.setText("  Student Id");
        }
    }//GEN-LAST:event_stdIdFocusLost

    private void stdIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdIdActionPerformed

    private void stdPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdPhoneFocusGained
         if(stdPhone.getText().equals("  Phone")){
            stdPhone.setText(null);
            stdPhone.requestFocus();
            mainPage.removePlaaceholderStytle(stdPhone);
        }
    }//GEN-LAST:event_stdPhoneFocusGained

    private void stdPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdPhoneFocusLost
       if(stdPhone.getText().length() == 0){
            mainPage.addPlaaceholderStytle(stdPhone);
            stdPhone.setText("  Phone");
        }
    }//GEN-LAST:event_stdPhoneFocusLost

    private void stdPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdPhoneActionPerformed

    private void stdGarNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdGarNameFocusGained
         if(stdGarName.getText().equals("  Gurdian name")){
            stdGarName.setText(null);
            stdGarName.requestFocus();
            mainPage.removePlaaceholderStytle(stdGarName);
        }
    }//GEN-LAST:event_stdGarNameFocusGained

    private void stdGarNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdGarNameFocusLost
        if(stdGarName.getText().length() == 0){
            mainPage.addPlaaceholderStytle(stdGarName);
            stdGarName.setText("  Gurdian name");
        }
    }//GEN-LAST:event_stdGarNameFocusLost

    private void stdGarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdGarNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdGarNameActionPerformed

    private void stdAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdAddressFocusGained
       if(stdAddress.getText().equals("  Address")){
            stdAddress.setText(null);
            stdAddress.requestFocus();
            mainPage.removePlaaceholderStytle(stdAddress);
        }
    }//GEN-LAST:event_stdAddressFocusGained

    private void stdAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdAddressFocusLost
        if(stdAddress.getText().length() == 0){
            mainPage.addPlaaceholderStytle(stdAddress);
            stdAddress.setText("  Address");
        }
    }//GEN-LAST:event_stdAddressFocusLost

    private void stdAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdAddressActionPerformed

    private void stdGarPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdGarPhoneFocusGained
        if(stdGarPhone.getText().equals("  Gurdian phone")){
            stdGarPhone.setText(null);
            stdGarPhone.requestFocus();
            mainPage.removePlaaceholderStytle(stdGarPhone);
        }
    }//GEN-LAST:event_stdGarPhoneFocusGained

    private void stdGarPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdGarPhoneFocusLost
        if(stdGarPhone.getText().length() == 0){
            mainPage.addPlaaceholderStytle(stdGarPhone);
            stdGarPhone.setText("  Gurdian phone");
        }
    }//GEN-LAST:event_stdGarPhoneFocusLost

    private void stdGarPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdGarPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdGarPhoneActionPerformed

    private void stdPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdPasswordFocusGained
        // TODO add your handling code here:
        if(stdPassword.getText().equals("  Student password")){
            stdPassword.setText(null);
            stdPassword.requestFocus();
            stdPassword.setEchoChar('*');
            mainPage.removePlaaceholderStytle(stdPassword);
        }
    }//GEN-LAST:event_stdPasswordFocusGained

    private void stdPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdPasswordFocusLost
        if(stdPassword.getText().length() == 0){
            mainPage.addPlaaceholderStytle(stdPassword);
            stdPassword.setText("  Student password");
            stdPassword.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_stdPasswordFocusLost

    private void stdPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdPasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String studentId = stdId.getText();
        String studentName = stdName.getText();
        String studentIntake = (String) stdIntake.getSelectedItem();
        String studentPhone = stdPhone.getText();
        String studentBirthDate = (String)stdBirthDate.getSelectedItem();
        String studentBirthMonth = (String)stdBirthMonth.getSelectedItem();
        String studentBirthYear = (String)stdBirthYear.getSelectedItem();
        String studentGender = (String)stdGender.getSelectedItem();
        String studentSemester = (String)stdSem.getSelectedItem();
        String studentYear = (String)stdYear.getSelectedItem();
        String studentDepartment = (String)stdDept.getSelectedItem();
        String studentGurdianName = stdGarName.getText();
        String studentGurdianRelation = (String)stdRelGurd.getSelectedItem();
        String studentGurdianPhone = stdGarPhone.getText();
        String studentPassword = stdPassword.getText();
        String studentAddress = stdAddress.getText();
        String studentdBirthDay = studentBirthMonth + " " + studentBirthDate + ", " + studentBirthYear;
       
        if(!checkReadyForDatabese){
            if(studentId.equals("  Student Id") || studentId.equals("")){
                JOptionPane.showMessageDialog(rootPane, "Useraname or ID is required");
            }else if(studentName.equals("  Student name") || studentName.equals("")){
                JOptionPane.showMessageDialog(rootPane, "Name is required");
            }else if(studentBirthDate.equals("day")){
                JOptionPane.showMessageDialog(rootPane, "Birth Date is required");
            }else if(studentBirthMonth.equals("month")){
                JOptionPane.showMessageDialog(rootPane, "Birth Month is required");
            }else if(studentBirthYear.equals("year")){
                JOptionPane.showMessageDialog(rootPane, "Birth Year is required");
            }else if(studentGender.equals("none")){
                JOptionPane.showMessageDialog(rootPane, "Gender is required");
            }else if(studentSemester.equals("none")){
                JOptionPane.showMessageDialog(rootPane, "Semester is required");
            }else if(studentYear.equals("year")){
                JOptionPane.showMessageDialog(rootPane, "Year is required");
            }else if(studentDepartment.equals("none")){
                JOptionPane.showMessageDialog(rootPane, "Department is required");
            }else if(studentIntake.equals("none")){
                JOptionPane.showMessageDialog(rootPane, "Intake is required");
            }else if(studentPhone.equals("  Phone") || studentId.equals("")){
                JOptionPane.showMessageDialog(rootPane, "Phone is required");
            }else if(studentGurdianName.equals("  Gurdian name") || studentGurdianName.equals("")){
                JOptionPane.showMessageDialog(rootPane, "Guardian name is required");
            }else if(studentGurdianRelation.equals("none")){
                JOptionPane.showMessageDialog(rootPane, "Guardian Relation is required");
            }else if(studentGurdianPhone.equals("  Gurdian phone")  || studentGurdianPhone.equals("")){
                JOptionPane.showMessageDialog(rootPane, "Guardian phone is required");
            }else if(studentPassword.equals("  Student password")  || studentPassword.equals("")){
                JOptionPane.showMessageDialog(rootPane, "Sudent Password is required");
            }else if(studentAddress.equals("  Address")  || studentAddress.equals("")){
                JOptionPane.showMessageDialog(rootPane, "Address is required");
            }else{
                checkReadyForDatabese = true;
            }
        }
        if(checkReadyForDatabese){
              
            //Connect With DataBase Start

            String url = "jdbc:mysql://127.0.0.1/studentmangementsystem";
            String user = "root";
            String password = "";

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                connection =  DriverManager.getConnection(url, user, password);
            } catch (SQLException ex) {
                Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
            }

            //Connect With DataBase End
            
            String insertQuery = "INSERT INTO stdinfo(stdId, stdName, stdIntake, stdPhone, stdBirth, stdGender, stdSemester, stdYear, stdDept, stdGar, stdGarRel, stdGarPhone, stdPasswor, stdAddress ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
           
            try {
                PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);
                preparedStatement.setString(1, studentId);
                preparedStatement.setString(2, studentName);
                preparedStatement.setString(3, studentIntake);
                preparedStatement.setString(4, studentPhone);
                preparedStatement.setString(5, studentdBirthDay);
                preparedStatement.setString(6, studentGender);
                preparedStatement.setString(7, studentSemester);
                preparedStatement.setString(8, studentYear);
                preparedStatement.setString(9, studentDepartment);
                preparedStatement.setString(10, studentGurdianName);
                preparedStatement.setString(11, studentGurdianRelation);
                preparedStatement.setString(12, studentGurdianPhone);
                preparedStatement.setString(13, studentPassword);
                preparedStatement.setString(14, studentAddress);
  
                preparedStatement.executeUpdate();
                regComplete = true;
         
            } catch (SQLException ex) {
                removeText(stdId);
                stdId.setText("  Student Id");
                JOptionPane.showMessageDialog(rootPane, "Student Id is Already Exist, Please Try with Differnt Id");
                regComplete = false;
                //Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
            }  
            checkReadyForDatabese = false;
        }
        
        if(regComplete){
            JOptionPane.showMessageDialog(rootPane, "Registration Complete");
            
            removeText(stdId);
            removeText(stdName);
            removeText(stdPhone);
            removeText(stdPassword);
            removeText(stdGarName);
            removeText(stdGarPhone);
            removeText(stdAddress);
            
            stdId.setText("  Student Id");
            stdName.setText("  Student name");
            stdIntake.setSelectedItem("none");
            stdPhone.setText("  Phone");
            stdGarName.setText("  Gurdian name");
            stdGarPhone.setText("  Gurdian phone");
            stdAddress.setText("  Address");
            stdPassword.setText("  Student password");
            stdPassword.setEchoChar('\u0000');
            stdDept.setSelectedItem("none");
            stdSem.setSelectedItem("none");
            stdBirthMonth.setSelectedItem("month");
            stdBirthDate.setSelectedItem("day");
            stdBirthYear.setSelectedItem("year");
            stdDept.setSelectedItem("noe");
            stdYear.setSelectedItem("year");
            stdGender.setSelectedItem("none");
            stdRelGurd.setSelectedItem("none");
            regComplete = false;
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void removeText(JTextField textField){   
        textField.setForeground(Color.gray);
    }
    
    private void logOutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseClicked
        if(!checkReadyForDatabese){
             mainPage.setVisible(true);
             this.dispose();
        }else{
            try {
                // TODO add your handling code here:
                connection.close();
            } catch (SQLException ex) {
                Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
            }
            checkReadyForDatabese = false;
            mainPage.setVisible(true);
            this.dispose();
        }
        
    
    }//GEN-LAST:event_logOutBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
          AdminMain adminMain = new AdminMain();
        if(!checkReadyForDatabese){
             adminMain.setVisible(true);
             this.dispose();
        }else{
            try {
                // TODO add your handling code here:
                connection.close();
            } catch (SQLException ex) {
                Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
            }
            checkReadyForDatabese = false;
            adminMain.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_backBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudent().setVisible(true);
            }
        });
        
        
      
    }

     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel logOutBtn;
    private javax.swing.JTextField stdAddress;
    private javax.swing.JComboBox<String> stdBirthDate;
    private javax.swing.JComboBox<String> stdBirthMonth;
    private javax.swing.JComboBox<String> stdBirthYear;
    private javax.swing.JComboBox<String> stdDept;
    private javax.swing.JTextField stdGarName;
    private javax.swing.JTextField stdGarPhone;
    private javax.swing.JComboBox<String> stdGender;
    private javax.swing.JTextField stdId;
    private javax.swing.JComboBox<String> stdIntake;
    private javax.swing.JTextField stdName;
    private javax.swing.JPasswordField stdPassword;
    private javax.swing.JTextField stdPhone;
    private javax.swing.JComboBox<String> stdRelGurd;
    private javax.swing.JComboBox<String> stdSem;
    private javax.swing.JComboBox<String> stdYear;
    // End of variables declaration//GEN-END:variables
}
