/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StudentManagement;

import java.sql.*;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aktaruzzaman
 */
public class StudentResult extends javax.swing.JFrame {

    Connection connection;
    boolean checkDatabaseConnect = false;
    MainPage mainPage;
    String studentId;

    /**
     * Creates new form StudentResult
     */
    public StudentResult() {
        initComponents();
        setResizable(false);
        setSize(1200, 700);
        mainPage = new MainPage();

        studentId = MainPage.passStudentId;

        studenetProfileIdResult.setText(studentId);
        studenetProfileNameResult.setText(StudentHome.studentNamsPass);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        studenetProfileNameResult = new javax.swing.JLabel();
        studenetProfileIdResult = new javax.swing.JLabel();
        backBtnStudent2 = new javax.swing.JLabel();
        logOutStudent2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        resultSemester = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        resultYear = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        showResult = new javax.swing.JLabel();
        resultSubmitBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/std_profile_iamge.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 96, -1, 154));

        studenetProfileNameResult.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        studenetProfileNameResult.setForeground(new java.awt.Color(2, 166, 118));
        studenetProfileNameResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studenetProfileNameResult.setText("Student Name");
        jPanel2.add(studenetProfileNameResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 262, 263, -1));

        studenetProfileIdResult.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        studenetProfileIdResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studenetProfileIdResult.setText("stuent Id");
        jPanel2.add(studenetProfileIdResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 297, 257, -1));

        backBtnStudent2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        backBtnStudent2.setForeground(new java.awt.Color(255, 255, 255));
        backBtnStudent2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backBtnStudent2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_black.png"))); // NOI18N
        backBtnStudent2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 166, 118), 1, true));
        backBtnStudent2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtnStudent2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnStudent2MouseClicked(evt);
            }
        });
        jPanel2.add(backBtnStudent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 533, 100, 55));

        logOutStudent2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        logOutStudent2.setForeground(new java.awt.Color(2, 166, 118));
        logOutStudent2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logOutStudent2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoutGreen.png"))); // NOI18N
        logOutStudent2.setText("Logout");
        logOutStudent2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 166, 118), 1, true));
        logOutStudent2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutStudent2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutStudent2MouseClicked(evt);
            }
        });
        jPanel2.add(logOutStudent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 533, 145, 55));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 700));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultSemester.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        resultSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "Spring", "Fall" }));
        resultSemester.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 166, 118), 1, true));
        jPanel4.add(resultSemester, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 350, 50));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 166, 118));
        jLabel1.setText("Semester");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        resultYear.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        resultYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "2023", "2024", "2025", "2026", "2027" }));
        resultYear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 166, 118), 1, true));
        jPanel4.add(resultYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 350, 50));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 166, 118));
        jLabel2.setText("Year");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        showResult.setBackground(new java.awt.Color(51, 204, 255));
        showResult.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        showResult.setForeground(new java.awt.Color(255, 102, 102));
        showResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showResult.setText("Your SGPA is:");
        jPanel4.add(showResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 350, -1));

        resultSubmitBtn.setBackground(new java.awt.Color(2, 166, 118));
        resultSubmitBtn.setFont(new java.awt.Font("Consolas", 0, 28)); // NOI18N
        resultSubmitBtn.setForeground(new java.awt.Color(255, 255, 255));
        resultSubmitBtn.setText("SUBMIT");
        resultSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultSubmitBtnActionPerformed(evt);
            }
        });
        jPanel4.add(resultSubmitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 140, 50));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 166, 118));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RESULT");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 250, 60));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 810, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnStudent2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnStudent2MouseClicked
        StudentHome studentHome = new StudentHome();
        if (checkDatabaseConnect) {
            try {
                connection.close();
            } catch (SQLException ex) {
                Logger.getLogger(StudentHome.class.getName()).log(Level.SEVERE, null, ex);
            }
            studentHome.setVisible(true);
            this.dispose();
        } else {
            studentHome.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_backBtnStudent2MouseClicked

    private void logOutStudent2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutStudent2MouseClicked
        if (checkDatabaseConnect) {
            try {
                connection.close();
            } catch (SQLException ex) {
                Logger.getLogger(StudentHome.class.getName()).log(Level.SEVERE, null, ex);
            }
            mainPage.setVisible(true);
            this.dispose();
        } else {
            mainPage.setVisible(true);
            this.dispose();
        }


    }//GEN-LAST:event_logOutStudent2MouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        requestFocusInWindow(true);
    }//GEN-LAST:event_formWindowGainedFocus

    private void resultSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultSubmitBtnActionPerformed
        String getSemester = resultSemester.getSelectedItem().toString();
        String getYear = resultYear.getSelectedItem().toString();

        if (getSemester.equals("none")) {
            JOptionPane.showMessageDialog(rootPane, "Semeter Field is Required");
        } else if (getYear.equals("none")) {
            JOptionPane.showMessageDialog(rootPane, "Year Field is Required");
        } else {
            String user = "root";
            String password = "";
            String url = "jdbc:mysql://localhost:3306/studentmangementsystem?serverTimezone=UTC";
            try {
                connection = DriverManager.getConnection(url, user, password);
                String querySelectCreditMark = "SELECT score, courseCredit FROM result WHERE stdId = ? AND semester = ? AND year = ?";
                PreparedStatement preparedStatementCreditMark = connection.prepareStatement(querySelectCreditMark);

                preparedStatementCreditMark.setString(1, studentId);
                preparedStatementCreditMark.setString(2, getSemester);
                preparedStatementCreditMark.setString(3, getYear);

                ResultSet resultSet = preparedStatementCreditMark.executeQuery();
                double SGPA = 0;

                if (resultSet.next()) {
                    double mark = resultSet.getDouble(1);
                    double credit = resultSet.getDouble(2);
                    SGPA += ResultCalculator.SGPA(credit, mark);

                    while (resultSet.next()) {
                        mark = resultSet.getDouble(1);
                        credit = resultSet.getDouble(2);
                        SGPA += ResultCalculator.SGPA(credit, mark);
                    }

                    preparedStatementCreditMark.close();
                    resultSet.close();

                    querySelectCreditMark = "SELECT SUM(courseCredit) FROM result WHERE stdId = ? AND semester = ? AND year = ?";
                    preparedStatementCreditMark = connection.prepareStatement(querySelectCreditMark);

                    preparedStatementCreditMark.setString(1, studentId);
                    preparedStatementCreditMark.setString(2, getSemester);
                    preparedStatementCreditMark.setString(3, getYear);
                    resultSet = preparedStatementCreditMark.executeQuery();

                    if (resultSet.next()) {
                        double totalCredit;
                        totalCredit = resultSet.getDouble(1);
                        SGPA /= totalCredit;
                        DecimalFormat df = new DecimalFormat("#.##");
                        String formattedSGPA = df.format(SGPA);
                        showResult.setText("Your " + getSemester + ", " + getYear + " SGPA is: " + formattedSGPA);
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Result not publish yet");
                    }

                    preparedStatementCreditMark.close();
                    resultSet.close();

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Result not publish yet");
                }

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }


    }//GEN-LAST:event_resultSubmitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBtnStudent2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logOutStudent2;
    private javax.swing.JComboBox<String> resultSemester;
    private javax.swing.JButton resultSubmitBtn;
    private javax.swing.JComboBox<String> resultYear;
    private javax.swing.JLabel showResult;
    public static javax.swing.JLabel studenetProfileIdResult;
    private javax.swing.JLabel studenetProfileNameResult;
    // End of variables declaration//GEN-END:variables
}
