/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StudentManagement;

import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aktaruzzaman
 */
public class StudentProfile extends javax.swing.JFrame {

    MainPage mainPage;
    ResultCalculator resultCalculator;
    Connection connection;
    protected static String stdProfileNamePass;
    protected static String studenetProfileIdPass;
    /**
     * Creates new form StudentProfile
     */
    public StudentProfile() {
        initComponents();
        setResizable(false);
        setSize(1200, 700);
        mainPage = new MainPage();
        resultCalculator = new ResultCalculator();
        getStudentInfo(MainPage.passStudentId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        studenetProfileProgram = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        studenetProfileSemester = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        studenetProfileYear = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        studenetProfileIntake = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        studenetProfileRegCourse = new javax.swing.JLabel();
        stuenetProfileComCourse = new javax.swing.JPanel();
        studenetProfileComCourse = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        studenetProfileCgpa = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        studenetProfilePhoneNumber = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        backBtnStudent = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        studentProfileBirthDate = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studenetProfileName = new javax.swing.JLabel();
        studenetProfileId = new javax.swing.JLabel();
        currentPassword = new javax.swing.JPasswordField();
        resetPassword = new javax.swing.JButton();
        newPassword = new javax.swing.JPasswordField();
        logOutStudent = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 56, 64));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Program");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 180, 40));

        jPanel4.setBackground(new java.awt.Color(0, 90, 91));

        studenetProfileProgram.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        studenetProfileProgram.setForeground(new java.awt.Color(255, 255, 255));
        studenetProfileProgram.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studenetProfileProgram.setText("ETC Scinece and Engineering ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(studenetProfileProgram)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(studenetProfileProgram)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 350, 40));

        jPanel6.setBackground(new java.awt.Color(0, 140, 114));

        studenetProfileSemester.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        studenetProfileSemester.setForeground(new java.awt.Color(255, 255, 255));
        studenetProfileSemester.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studenetProfileSemester.setText("Defaul Semester");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(studenetProfileSemester)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studenetProfileSemester)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 350, 40));

        jPanel5.setBackground(new java.awt.Color(0, 115, 105));
        jPanel5.setForeground(new java.awt.Color(0, 115, 105));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Semester");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 180, 40));

        jPanel9.setBackground(new java.awt.Color(0, 115, 105));
        jPanel9.setForeground(new java.awt.Color(0, 115, 105));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Intake");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(79, 79, 79))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 180, 40));

        jPanel8.setBackground(new java.awt.Color(0, 56, 64));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Year");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 180, 40));

        jPanel7.setBackground(new java.awt.Color(0, 90, 91));

        studenetProfileYear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        studenetProfileYear.setForeground(new java.awt.Color(255, 255, 255));
        studenetProfileYear.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studenetProfileYear.setText("0000");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(studenetProfileYear)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studenetProfileYear)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 350, 40));

        jPanel10.setBackground(new java.awt.Color(0, 140, 114));

        studenetProfileIntake.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        studenetProfileIntake.setForeground(new java.awt.Color(255, 255, 255));
        studenetProfileIntake.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studenetProfileIntake.setText("00");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(studenetProfileIntake)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studenetProfileIntake)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 350, 40));

        jPanel11.setBackground(new java.awt.Color(0, 56, 64));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Register Course");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 180, 40));

        jPanel12.setBackground(new java.awt.Color(0, 90, 91));

        studenetProfileRegCourse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        studenetProfileRegCourse.setForeground(new java.awt.Color(255, 255, 255));
        studenetProfileRegCourse.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studenetProfileRegCourse.setText("00");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(studenetProfileRegCourse)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(studenetProfileRegCourse)
                .addContainerGap())
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 350, 40));

        stuenetProfileComCourse.setBackground(new java.awt.Color(0, 140, 114));

        studenetProfileComCourse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        studenetProfileComCourse.setForeground(new java.awt.Color(255, 255, 255));
        studenetProfileComCourse.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studenetProfileComCourse.setText("00");

        javax.swing.GroupLayout stuenetProfileComCourseLayout = new javax.swing.GroupLayout(stuenetProfileComCourse);
        stuenetProfileComCourse.setLayout(stuenetProfileComCourseLayout);
        stuenetProfileComCourseLayout.setHorizontalGroup(
            stuenetProfileComCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stuenetProfileComCourseLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(studenetProfileComCourse)
                .addContainerGap(297, Short.MAX_VALUE))
        );
        stuenetProfileComCourseLayout.setVerticalGroup(
            stuenetProfileComCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stuenetProfileComCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studenetProfileComCourse)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(stuenetProfileComCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 350, 40));

        jPanel17.setBackground(new java.awt.Color(0, 90, 91));

        studenetProfileCgpa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        studenetProfileCgpa.setForeground(new java.awt.Color(255, 255, 255));
        studenetProfileCgpa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studenetProfileCgpa.setText("00");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(studenetProfileCgpa)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studenetProfileCgpa)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 350, 40));

        jPanel15.setBackground(new java.awt.Color(0, 115, 105));
        jPanel15.setForeground(new java.awt.Color(0, 115, 105));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Phone no");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(123, 123, 123))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 180, 40));

        jPanel18.setBackground(new java.awt.Color(0, 140, 114));

        studenetProfilePhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        studenetProfilePhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        studenetProfilePhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studenetProfilePhoneNumber.setText("01000000000000");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(studenetProfilePhoneNumber)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studenetProfilePhoneNumber)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 350, 40));

        jPanel16.setBackground(new java.awt.Color(0, 56, 64));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cgpa");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(119, 119, 119))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 180, 40));

        jPanel14.setBackground(new java.awt.Color(0, 115, 105));
        jPanel14.setForeground(new java.awt.Color(0, 115, 105));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Completed Course");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 180, 40));

        backBtnStudent.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        backBtnStudent.setForeground(new java.awt.Color(255, 255, 255));
        backBtnStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backBtnStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_black.png"))); // NOI18N
        backBtnStudent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 166, 118), 1, true));
        backBtnStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtnStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnStudentMouseClicked(evt);
            }
        });
        jPanel1.add(backBtnStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 100, 55));

        jPanel19.setBackground(new java.awt.Color(0, 56, 64));
        jPanel19.setForeground(new java.awt.Color(0, 115, 105));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Birth Date");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 180, 40));

        jPanel20.setBackground(new java.awt.Color(0, 90, 91));

        studentProfileBirthDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        studentProfileBirthDate.setForeground(new java.awt.Color(255, 255, 255));
        studentProfileBirthDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studentProfileBirthDate.setText("day month,year");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(studentProfileBirthDate)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentProfileBirthDate)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 350, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 800, 700));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/std_profile_iamge.png"))); // NOI18N

        studenetProfileName.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        studenetProfileName.setForeground(new java.awt.Color(2, 166, 118));
        studenetProfileName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studenetProfileName.setText("Student Name");

        studenetProfileId.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        studenetProfileId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studenetProfileId.setText("stuent Id");

        currentPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        currentPassword.setForeground(new java.awt.Color(153, 153, 153));
        currentPassword.setText("   Enter your current password");
        currentPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 166, 118), 1, true));
        currentPassword.setEchoChar('\u0000');
        currentPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                currentPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                currentPasswordFocusLost(evt);
            }
        });
        currentPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentPasswordActionPerformed(evt);
            }
        });

        resetPassword.setBackground(new java.awt.Color(2, 166, 118));
        resetPassword.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        resetPassword.setForeground(new java.awt.Color(255, 255, 255));
        resetPassword.setText("RESET PASSWORD");
        resetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetPasswordActionPerformed(evt);
            }
        });

        newPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        newPassword.setForeground(new java.awt.Color(153, 153, 153));
        newPassword.setText("   Enter your new password");
        newPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 166, 118), 1, true));
        newPassword.setEchoChar('\u0000');
        newPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                newPasswordFocusLost(evt);
            }
        });
        newPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordActionPerformed(evt);
            }
        });

        logOutStudent.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        logOutStudent.setForeground(new java.awt.Color(2, 166, 118));
        logOutStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logOutStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoutGreen.png"))); // NOI18N
        logOutStudent.setText("Logout");
        logOutStudent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 166, 118), 1, true));
        logOutStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutStudentMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studenetProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studenetProfileId, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(resetPassword))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(logOutStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(132, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studenetProfileName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studenetProfileId)
                .addGap(43, 43, 43)
                .addComponent(currentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(519, Short.MAX_VALUE)
                    .addComponent(logOutStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(126, 126, 126)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getStudentInfo(String receiveStudentId) {
        try {
            // Connect to the database
            String user = "root";
            String password = "";
            String url = "jdbc:mysql://localhost:3306/studentmangementsystem?serverTimezone=UTC";
            connection = DriverManager.getConnection(url, user, password);

            //Select Name
            String queryForRetriveStdInfo = "SELECT * FROM stdinfo WHERE stdId = ?";
            PreparedStatement preparedStatement = connection.prepareStatement(queryForRetriveStdInfo);
            preparedStatement.setString(1, receiveStudentId);

            ResultSet resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                stdProfileNamePass = resultSet.getString("stdName");
                studenetProfileIdPass = resultSet.getString("stdId");
                studenetProfileName.setText(resultSet.getString("stdName"));
                studenetProfileId.setText(resultSet.getString("stdId"));
                studenetProfileProgram.setText(resultSet.getString("stdDept"));
                studenetProfileSemester.setText(resultSet.getString("stdSemester"));
                studenetProfilePhoneNumber.setText(resultSet.getString("stdPhone"));
                studenetProfileYear.setText(resultSet.getString("stdYear"));
                studenetProfileIntake.setText(resultSet.getString("stdIntake"));
                studentProfileBirthDate.setText(resultSet.getString("stdBirth"));
                studenetProfileRegCourse.setText(StudentHome.count);
            }

            resultSet.close();
            preparedStatement.close();

            String comCourseCount = "SELECT COUNT(stdId) FROM result WHERE stdId = ?";
            preparedStatement = connection.prepareStatement(comCourseCount);
            preparedStatement.setString(1, receiveStudentId);
            resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                String comCourse = Integer.toString(resultSet.getInt(1));
                studenetProfileComCourse.setText(comCourse);

            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
        String getResult = resultCalculator.CGPA(receiveStudentId);
        
        if(getResult != null && !(getResult.equals(""))){
            studenetProfileCgpa.setText(getResult);
        }else{
             studenetProfileCgpa.setText("00");
        }
        
        
    }

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        requestFocusInWindow(true);
    }//GEN-LAST:event_formWindowGainedFocus

    private void currentPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_currentPasswordFocusGained
        if (currentPassword.getText().equals("   Enter your current password")) {
            currentPassword.setText(null);
            currentPassword.requestFocus();
            currentPassword.setEchoChar('*');
            mainPage.removePlaaceholderStytle(currentPassword);
        }
    }//GEN-LAST:event_currentPasswordFocusGained

    private void currentPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_currentPasswordFocusLost
        // TODO add your handling code here:
        if (currentPassword.getText().length() == 0) {
            MainPage.addPlaaceholderStytle(currentPassword);
            currentPassword.setText("   Enter your current password");
            currentPassword.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_currentPasswordFocusLost

    private void currentPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentPasswordActionPerformed
        //Enter your phone number
    }//GEN-LAST:event_currentPasswordActionPerformed

    private void resetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetPasswordActionPerformed
        // TODO add your handling code here:
        String usercurrentPassword = currentPassword.getText();
        String userNewPass = newPassword.getText();

        if (usercurrentPassword.equals("") || usercurrentPassword.equals("   Enter your current password")) {
            JOptionPane.showMessageDialog(rootPane, "Please Enter Your current Password");
        } else if (userNewPass.equals("") || userNewPass.equals("   Enter your new password")) {
            JOptionPane.showMessageDialog(rootPane, "Please Enter Your new Password");
        } else {
            try {

                String resetPassStdId = MainPage.passStudentId;
                String currentPasswordInput = currentPassword.getText();
                String newPasswordInput = newPassword.getText();

                if (currentPasswordInput.equals("") || currentPasswordInput.equals("   Enter your current password")) {
                    JOptionPane.showMessageDialog(rootPane, "Current password field required");
                } else if (newPasswordInput.equals("") || newPasswordInput.equals("   Enter your current password")) {
                    JOptionPane.showMessageDialog(rootPane, "New password field required");
                } else {
                    // Connect to the database
                    String user = "root";
                    String password = "";
                    String url = "jdbc:mysql://localhost:3306/studentmangementsystem?serverTimezone=UTC";
                    connection = DriverManager.getConnection(url, user, password);
                    String queryForRetrivePass = "SELECT stdPasswor FROM stdinfo WHERE stdId = ?";
                    PreparedStatement preparedStatement = connection.prepareStatement(queryForRetrivePass);
                    preparedStatement.setString(1, resetPassStdId);
                    
                    ResultSet resultSet = preparedStatement.executeQuery();
                    
                    if(resultSet.next()){
                        if(resultSet.getString("stdPasswor").equals(currentPasswordInput)){
                            
                             String queryForResetPass = "UPDATE stdinfo SET stdPasswor = ? WHERE stdId = ?";
                             PreparedStatement statementForResetPass = connection.prepareStatement(queryForResetPass);
                             statementForResetPass.setString(1, newPasswordInput);
                             statementForResetPass.setString(2, resetPassStdId);
                             
                             int effect = statementForResetPass.executeUpdate();
                             
                             if(effect > 0){
                                  JOptionPane.showMessageDialog(rootPane, "Sucessfully reset password");
                             }else{
                                JOptionPane.showMessageDialog(rootPane, "Faild to reset password");
                             }
                            statementForResetPass.close();
                             
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "Incorrect current password");
                        }
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Faild to reset password");
                    }
                    
                    resultSet.close();
                    preparedStatement.close();

                }
                

            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

        newPassword.setText("   Enter your new password");
        newPassword.setForeground(Color.gray);
        newPassword.setEchoChar('\u0000');
        currentPassword.setText("   Enter your current password");
        currentPassword.setForeground(Color.gray);
        currentPassword.setEchoChar('\u0000');
    }//GEN-LAST:event_resetPasswordActionPerformed

    private void newPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newPasswordFocusGained
        if (newPassword.getText().equals("   Enter your new password")) {
            newPassword.setText(null);
            newPassword.requestFocus();
            newPassword.setEchoChar('*');
            mainPage.removePlaaceholderStytle(newPassword);
        }
    }//GEN-LAST:event_newPasswordFocusGained

    private void newPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newPasswordFocusLost
        // TODO add your handling code here:
        if (newPassword.getText().length() == 0) {
            MainPage.addPlaaceholderStytle(newPassword);
            newPassword.setText("   Enter your new password");
            newPassword.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_newPasswordFocusLost

    private void newPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPasswordActionPerformed

    private void backBtnStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnStudentMouseClicked
        try {
            connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(StudentHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        StudentHome studentHome = new StudentHome();
        studentHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnStudentMouseClicked

    private void logOutStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutStudentMouseClicked
        try {
            connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(StudentHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        mainPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutStudentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBtnStudent;
    private javax.swing.JPasswordField currentPassword;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel logOutStudent;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JButton resetPassword;
    private javax.swing.JLabel studenetProfileCgpa;
    private javax.swing.JLabel studenetProfileComCourse;
    private javax.swing.JLabel studenetProfileId;
    private javax.swing.JLabel studenetProfileIntake;
    private javax.swing.JLabel studenetProfileName;
    private javax.swing.JLabel studenetProfilePhoneNumber;
    private javax.swing.JLabel studenetProfileProgram;
    private javax.swing.JLabel studenetProfileRegCourse;
    private javax.swing.JLabel studenetProfileSemester;
    private javax.swing.JLabel studenetProfileYear;
    private javax.swing.JLabel studentProfileBirthDate;
    private javax.swing.JPanel stuenetProfileComCourse;
    // End of variables declaration//GEN-END:variables
}
