/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StudentManagement;


import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Aktaruzzaman
 */
public class StudentDemand extends javax.swing.JFrame {
    Connection connection;
    MainPage mainPage;
    /**
     * Creates new form StudentDemand
     */
    public StudentDemand() {
        initComponents();
        mainPage = new MainPage();
        setResizable(false);
        setSize(1200,700);
        getStudentInfo(MainPage.passStudentId);
    }
    
    private void getStudentInfo(String receiveStudentId) {
        studenetProfileIdDemand.setText(receiveStudentId);
        studenetProfileNameDemand.setText(StudentHome.studentNamsPass);
        try {
            // Connect to the database
            String user = "root";
            String password = "";
            String url = "jdbc:mysql://localhost:3306/studentmangementsystem?serverTimezone=UTC";
            connection = DriverManager.getConnection(url, user, password);

            //Select Name
            String queryForRetriveDemand = "SELECT * FROM demand WHERE stdId = ?";
            PreparedStatement preparedStatement = connection.prepareStatement(queryForRetriveDemand);
            preparedStatement.setString(1, receiveStudentId);
            
            ResultSet resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
               tutionFee.setText(" "+ resultSet.getString("tutionFee"));
               libraryFee.setText(" "+ resultSet.getString("librayFee"));
               LabFee.setText(" "+ resultSet.getString("labFee"));
               MedicalFee.setText(" "+ resultSet.getString("medicalFee"));
               othersFee.setText(" "+ resultSet.getString("otherFee"));
               TotalDemand.setText(" "+ resultSet.getString("toatalFee"));
            }

            resultSet.close();
            preparedStatement.close();

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        studenetProfileNameDemand = new javax.swing.JLabel();
        studenetProfileIdDemand = new javax.swing.JLabel();
        logOutStudent2 = new javax.swing.JLabel();
        backBtnStudent2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        courseNameOne = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        LabFee = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        tutionFee = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        libraryFee = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        courseNameOne2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        MedicalFee = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        othersFee = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        courseNameOne4 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        TotalDemand = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        courseNameOne7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setBackground(new java.awt.Color(250, 250, 250));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/std_profile_iamge.png"))); // NOI18N
        jPanel23.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 160, -1, 154));

        studenetProfileNameDemand.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        studenetProfileNameDemand.setForeground(new java.awt.Color(2, 166, 118));
        studenetProfileNameDemand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studenetProfileNameDemand.setText("Student Name");
        jPanel23.add(studenetProfileNameDemand, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 326, 263, -1));

        studenetProfileIdDemand.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        studenetProfileIdDemand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studenetProfileIdDemand.setText("stuent Id");
        jPanel23.add(studenetProfileIdDemand, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 361, 257, -1));

        logOutStudent2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        logOutStudent2.setForeground(new java.awt.Color(2, 166, 118));
        logOutStudent2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logOutStudent2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoutGreen.png"))); // NOI18N
        logOutStudent2.setText("Logout");
        logOutStudent2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 166, 118), 1, true));
        logOutStudent2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutStudent2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutStudent2MouseClicked(evt);
            }
        });
        jPanel23.add(logOutStudent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 419, 145, 55));

        backBtnStudent2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        backBtnStudent2.setForeground(new java.awt.Color(255, 255, 255));
        backBtnStudent2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backBtnStudent2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_black.png"))); // NOI18N
        backBtnStudent2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 166, 118), 1, true));
        backBtnStudent2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtnStudent2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnStudent2MouseClicked(evt);
            }
        });
        jPanel23.add(backBtnStudent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 419, 100, 55));

        jPanel1.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 56, 64));

        jLabel7.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" Tution Fee");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 210, 40));

        jPanel7.setBackground(new java.awt.Color(0, 90, 91));
        jPanel7.setForeground(new java.awt.Color(0, 115, 105));

        courseNameOne.setBackground(new java.awt.Color(0, 90, 91));
        courseNameOne.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        courseNameOne.setForeground(new java.awt.Color(255, 255, 255));
        courseNameOne.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        courseNameOne.setText("Lab Fee");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(courseNameOne, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courseNameOne, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 210, 40));

        jPanel10.setBackground(new java.awt.Color(0, 115, 105));
        jPanel10.setForeground(new java.awt.Color(0, 115, 105));

        LabFee.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        LabFee.setForeground(new java.awt.Color(255, 255, 255));
        LabFee.setText(" 00");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(LabFee, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(LabFee, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 200, 40));

        jPanel5.setBackground(new java.awt.Color(0, 90, 91));

        tutionFee.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        tutionFee.setForeground(new java.awt.Color(255, 255, 255));
        tutionFee.setText(" 00");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(tutionFee, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tutionFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 200, 40));

        jPanel15.setBackground(new java.awt.Color(0, 90, 91));

        libraryFee.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        libraryFee.setForeground(new java.awt.Color(255, 255, 255));
        libraryFee.setText(" 00");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(libraryFee, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(libraryFee, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        jPanel2.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 200, 40));

        jPanel6.setBackground(new java.awt.Color(0, 56, 64));

        jLabel8.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Library Fee");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 210, 40));

        jPanel13.setBackground(new java.awt.Color(0, 90, 91));
        jPanel13.setForeground(new java.awt.Color(0, 115, 105));

        courseNameOne2.setBackground(new java.awt.Color(0, 90, 91));
        courseNameOne2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        courseNameOne2.setForeground(new java.awt.Color(255, 255, 255));
        courseNameOne2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        courseNameOne2.setText("Medical Fee");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(courseNameOne2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courseNameOne2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 210, 40));

        jPanel14.setBackground(new java.awt.Color(0, 115, 105));
        jPanel14.setForeground(new java.awt.Color(0, 115, 105));

        MedicalFee.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        MedicalFee.setForeground(new java.awt.Color(255, 255, 255));
        MedicalFee.setText(" 00");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MedicalFee, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(MedicalFee, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        jPanel2.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 200, 40));

        jPanel17.setBackground(new java.awt.Color(0, 90, 91));
        jPanel17.setForeground(new java.awt.Color(0, 115, 105));

        othersFee.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        othersFee.setForeground(new java.awt.Color(255, 255, 255));
        othersFee.setText(" 00");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(othersFee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(othersFee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 200, 40));

        jPanel16.setBackground(new java.awt.Color(0, 56, 64));
        jPanel16.setForeground(new java.awt.Color(0, 115, 105));

        courseNameOne4.setBackground(new java.awt.Color(0, 90, 91));
        courseNameOne4.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        courseNameOne4.setForeground(new java.awt.Color(255, 255, 255));
        courseNameOne4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        courseNameOne4.setText("Others Fee");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(courseNameOne4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courseNameOne4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 210, 40));

        jPanel18.setBackground(new java.awt.Color(255, 153, 153));
        jPanel18.setForeground(new java.awt.Color(0, 115, 105));

        TotalDemand.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        TotalDemand.setText(" 00");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TotalDemand, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TotalDemand, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 200, 40));

        jPanel19.setBackground(new java.awt.Color(255, 102, 102));
        jPanel19.setForeground(new java.awt.Color(0, 115, 105));

        courseNameOne7.setBackground(new java.awt.Color(0, 90, 91));
        courseNameOne7.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        courseNameOne7.setForeground(new java.awt.Color(255, 255, 255));
        courseNameOne7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        courseNameOne7.setText("Total Demand");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(courseNameOne7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(courseNameOne7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 210, 40));

        jPanel3.setBackground(new java.awt.Color(0, 153, 102));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Consolas", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CURRENT SEMESTER DEMAND");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 410, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 750, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutStudent2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutStudent2MouseClicked
        try {
            connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(StudentDemand.class.getName()).log(Level.SEVERE, null, ex);
        }
        mainPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutStudent2MouseClicked

    private void backBtnStudent2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnStudent2MouseClicked
        try {
            connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(StudentDemand.class.getName()).log(Level.SEVERE, null, ex);
        }
        StudentHome studentHome = new StudentHome();
        studentHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnStudent2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDemand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDemand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDemand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDemand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDemand().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabFee;
    private javax.swing.JLabel MedicalFee;
    private javax.swing.JLabel TotalDemand;
    private javax.swing.JLabel backBtnStudent2;
    private javax.swing.JLabel courseNameOne;
    private javax.swing.JLabel courseNameOne2;
    private javax.swing.JLabel courseNameOne4;
    private javax.swing.JLabel courseNameOne7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel libraryFee;
    private javax.swing.JLabel logOutStudent2;
    private javax.swing.JLabel othersFee;
    public static javax.swing.JLabel studenetProfileIdDemand;
    private javax.swing.JLabel studenetProfileNameDemand;
    private javax.swing.JLabel tutionFee;
    // End of variables declaration//GEN-END:variables
}
