/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StudentManagement;
import com.mysql.cj.util.StringUtils;
import java.sql.*;
import java.util.logging.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Aktaruzzaman
 */
public class UpdateStudent extends javax.swing.JFrame {
    boolean checkReadyForDatabese = false;
    Connection connection;
    MainPage mainPage;
    AddStudent addStudent;
    boolean updateComplete = false;
    String searchStudentId;
    /**
     * Creates new form UpdateStuenet
     */
    public UpdateStudent() {
        initComponents();
        setResizable(false);
        this.setSize(1200, 700);
        mainPage = new MainPage();
        addStudent = new AddStudent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        logOutBtn1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        backBtnFromDelete = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        deleteStudentText = new javax.swing.JLabel();
        searchStdId = new javax.swing.JTextField();
        searchStudentBtn = new javax.swing.JPanel();
        searchStudent = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        stdBirthDate = new javax.swing.JComboBox<>();
        stdBirthMonth = new javax.swing.JComboBox<>();
        stdBirthYear = new javax.swing.JComboBox<>();
        stdGender = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        stdDept = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        stdGarName = new javax.swing.JTextField();
        stdRelGurd = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        stdAddress = new javax.swing.JTextField();
        stdGarPhone = new javax.swing.JTextField();
        updateStdBtn = new javax.swing.JButton();
        stdName = new javax.swing.JTextField();
        stdIntake = new javax.swing.JTextField();
        stdPhone = new javax.swing.JTextField();
        stdSem = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        stdYear = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Student");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(65, 71, 213));
        jPanel5.setPreferredSize(new java.awt.Dimension(115, 45));

        logOutBtn1.setBackground(new java.awt.Color(0, 153, 204));
        logOutBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logOutBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logOutBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutBtn1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(logOutBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutBtn1))
        );

        jPanel11.setBackground(new java.awt.Color(65, 71, 213));
        jPanel11.setFocusCycleRoot(true);
        jPanel11.setPreferredSize(new java.awt.Dimension(115, 45));

        backBtnFromDelete.setBackground(new java.awt.Color(0, 153, 204));
        backBtnFromDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backBtnFromDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        backBtnFromDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtnFromDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnFromDeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(backBtnFromDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtnFromDelete))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        deleteStudentText.setBackground(new java.awt.Color(0, 204, 255));
        deleteStudentText.setFont(new java.awt.Font("Showcard Gothic", 0, 35)); // NOI18N
        deleteStudentText.setForeground(new java.awt.Color(65, 71, 213));
        deleteStudentText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteStudentText.setText("UPDATE student");

        searchStdId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchStdId.setText("  Enter Student Id");
        searchStdId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 71, 213)));
        searchStdId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchStdIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchStdIdFocusLost(evt);
            }
        });
        searchStdId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStdIdActionPerformed(evt);
            }
        });

        searchStudentBtn.setBackground(new java.awt.Color(65, 71, 213));
        searchStudentBtn.setPreferredSize(new java.awt.Dimension(115, 45));
        searchStudentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchStudentBtnMouseClicked(evt);
            }
        });

        searchStudent.setBackground(new java.awt.Color(65, 71, 213));
        searchStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_icon.png"))); // NOI18N
        searchStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchStudentMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout searchStudentBtnLayout = new javax.swing.GroupLayout(searchStudentBtn);
        searchStudentBtn.setLayout(searchStudentBtnLayout);
        searchStudentBtnLayout.setHorizontalGroup(
            searchStudentBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchStudentBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        searchStudentBtnLayout.setVerticalGroup(
            searchStudentBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchStudentBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updatePageHeadingIcon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(searchStdId, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(deleteStudentText, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(searchStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(deleteStudentText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchStdId, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Year");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Date of Birth");

        stdBirthDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdBirthDate.setForeground(new java.awt.Color(255, 255, 255));
        stdBirthDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        stdBirthDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 71, 213)));

        stdBirthMonth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdBirthMonth.setForeground(new java.awt.Color(255, 255, 255));
        stdBirthMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        stdBirthMonth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 71, 213)));

        stdBirthYear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdBirthYear.setForeground(new java.awt.Color(255, 255, 255));
        stdBirthYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "year", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980" }));
        stdBirthYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 71, 213)));

        stdGender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdGender.setForeground(new java.awt.Color(255, 255, 255));
        stdGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "Male", "Female" }));
        stdGender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 71, 213)));
        stdGender.setPreferredSize(new java.awt.Dimension(324, 31));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Gender");

        stdDept.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdDept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "Computer Science and Engineering" }));
        stdDept.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 71, 213)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Department");

        stdGarName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdGarName.setText("  Gurdian name");
        stdGarName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 71, 213)));
        stdGarName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stdGarNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stdGarNameFocusLost(evt);
            }
        });
        stdGarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdGarNameActionPerformed(evt);
            }
        });

        stdRelGurd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdRelGurd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "Father", "Mother", "Brother", "Sister" }));
        stdRelGurd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 71, 213)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Relation with gurdian");

        stdAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdAddress.setText("  Address");
        stdAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 71, 213)));
        stdAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stdAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stdAddressFocusLost(evt);
            }
        });
        stdAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdAddressActionPerformed(evt);
            }
        });

        stdGarPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdGarPhone.setText("  Gurdian phone");
        stdGarPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 71, 213)));
        stdGarPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stdGarPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stdGarPhoneFocusLost(evt);
            }
        });
        stdGarPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdGarPhoneActionPerformed(evt);
            }
        });

        updateStdBtn.setBackground(new java.awt.Color(65, 71, 213));
        updateStdBtn.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        updateStdBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateStdBtn.setText("UPDATE");
        updateStdBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateStdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStdBtnActionPerformed(evt);
            }
        });

        stdName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdName.setText("  Student name");
        stdName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 71, 213)));
        stdName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stdNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stdNameFocusLost(evt);
            }
        });
        stdName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdNameActionPerformed(evt);
            }
        });

        stdIntake.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdIntake.setText("  Intake");
        stdIntake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 71, 213)));
        stdIntake.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stdIntakeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stdIntakeFocusLost(evt);
            }
        });
        stdIntake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdIntakeActionPerformed(evt);
            }
        });

        stdPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdPhone.setText("  Phone");
        stdPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 71, 213)));
        stdPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stdPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stdPhoneFocusLost(evt);
            }
        });
        stdPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdPhoneActionPerformed(evt);
            }
        });

        stdSem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdSem.setForeground(new java.awt.Color(255, 255, 255));
        stdSem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "Fall", "Spring" }));
        stdSem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 71, 213)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Semester");

        stdYear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stdYear.setForeground(new java.awt.Color(255, 255, 255));
        stdYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "year", "2018", "2019", "2020", "2021", "2022", "2023" }));
        stdYear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(65, 71, 213)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateStdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stdName)
                    .addComponent(stdAddress)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stdPhone)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(stdBirthDate, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(stdBirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(stdBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(stdSem, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(stdDept, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(stdYear, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(stdIntake, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(stdGarName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
                                    .addComponent(stdGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stdRelGurd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(stdGarPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(stdName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stdGender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(stdBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdBirthMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdBirthYear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stdSem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stdYear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stdDept, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stdIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stdPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stdGarName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stdRelGurd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stdGarPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(stdAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateStdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        requestFocusInWindow(true);
    }//GEN-LAST:event_formWindowGainedFocus

    private void searchStudentBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchStudentBtnMouseClicked
       

    }//GEN-LAST:event_searchStudentBtnMouseClicked

    private void searchStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchStudentMouseClicked
         try {
    // Connect to the database
            String user = "root";
            String password = "";
            String url = "jdbc:mysql://localhost:3306/studentmangementsystem?serverTimezone=UTC";
            connection = DriverManager.getConnection(url, user, password);

            // Retrieve the ID from the text field
            searchStudentId = searchStdId.getText();

            // Prepare a SELECT statement to check if the ID exists
            String checkIdQuery = "SELECT stdId FROM stdinfo WHERE stdId = ?";
            PreparedStatement checkIdStatement = connection.prepareStatement(checkIdQuery);
            checkIdStatement.setString(1, searchStudentId);

            // Execute the SELECT statement
            ResultSet checkIdResultSet = checkIdStatement.executeQuery();
           
            // Process the result
            if (checkIdResultSet.next()) {
                // ID exists, select all attributes
                String selectAllQuery = "SELECT * FROM stdinfo WHERE stdId = ?";
                PreparedStatement selectAllStatement = connection.prepareStatement(selectAllQuery);
                selectAllStatement.setString(1, searchStudentId);

                ResultSet selectAllResultSet = selectAllStatement.executeQuery();
 
                if (selectAllResultSet.next()) {
                    // Retrieve and display the attributes
                    String setStdName = selectAllResultSet.getString("stdName");
                    String setStdIntake = selectAllResultSet.getString("stdIntake");
                    String setStdPhone = selectAllResultSet.getString("stdPhone");
                    String getBirth = selectAllResultSet.getString("stdBirth");
                    
                    
                    String[] setBirthDivide = (getBirth.replace(",","")).split(" ");
                    String setStdBirthMonth = setBirthDivide[0];
                    String setStdBirhtDay =  setBirthDivide[1];
                    String setStdBirthYear =  setBirthDivide[2];
                                  
                    
                    String setStdGender = selectAllResultSet.getString("stdGender");
                    String setStdSemester = selectAllResultSet.getString("stdSemester");
                    String setStdYear = selectAllResultSet.getString("stdYear");
                    String setStdStdDept = selectAllResultSet.getString("stdDept");
                    String setStdGur = selectAllResultSet.getString("stdGar");
                    String setStdGurRel = selectAllResultSet.getString("stdGarRel");
                    String setStdGarPhone = selectAllResultSet.getString("stdGarPhone");
                    String setStdAddress = selectAllResultSet.getString("stdAddress");
                    
                    
                    stdIntake.setText(setStdIntake);
                    stdPhone.setText(setStdPhone);
                    stdName.setText(setStdName);
                    stdBirthDate.setSelectedItem(setStdBirhtDay);
                    stdBirthMonth.setSelectedItem(setStdBirthMonth);
                    stdBirthYear.setSelectedItem(setStdBirthYear);
                    stdGender.setSelectedItem(setStdGender);
                    stdSem.setSelectedItem(setStdSemester);
                    stdDept.setSelectedItem(setStdStdDept);
                    stdYear.setSelectedItem(setStdYear);
                    stdGarName.setText(setStdGur);
                    stdRelGurd.setSelectedItem(setStdGurRel);
                    stdGarPhone.setText(setStdGarPhone);
                    stdAddress.setText(setStdAddress);

                } else {
                    System.out.println("No attributes found for student ID " + searchStudentId);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Student ID " + searchStudentId + " does not exist.", "Invalid ID", JOptionPane.ERROR_MESSAGE);
            }

          
           connection.close();
        } catch (SQLException e) {
        } 
       
    }//GEN-LAST:event_searchStudentMouseClicked

    private void searchStdIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStdIdActionPerformed

    }//GEN-LAST:event_searchStdIdActionPerformed

    private void searchStdIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchStdIdFocusLost
        // TODO add your handling code here:
        if(searchStdId.getText().length() == 0){
            MainPage.addPlaaceholderStytle(searchStdId);
            searchStdId.setText("  Enter Student Id");
        }
    }//GEN-LAST:event_searchStdIdFocusLost

    private void searchStdIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchStdIdFocusGained
        if(searchStdId.getText().equals("  Enter Student Id")){
            searchStdId.setText(null);
            searchStdId.requestFocus();
            mainPage.removePlaaceholderStytle(searchStdId);
        }
    }//GEN-LAST:event_searchStdIdFocusGained

    private void backBtnFromDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnFromDeleteMouseClicked
        AdminOpearation adminOpearation = new AdminOpearation();
        if(!checkReadyForDatabese){
            adminOpearation.setVisible(true);
            this.dispose();
        }else{
            try {
                // TODO add your handling code here:
                connection.close();
            } catch (SQLException ex) {
                Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
            }
            checkReadyForDatabese = false;
            adminOpearation.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_backBtnFromDeleteMouseClicked

    private void logOutBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtn1MouseClicked
        if(!checkReadyForDatabese){
            mainPage.setVisible(true);
            this.dispose();
        }else{
            try {
                connection.close();
            } catch (SQLException ex) {
                Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
            }
            checkReadyForDatabese = false;
            mainPage.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logOutBtn1MouseClicked

    private void stdGarNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdGarNameFocusGained
        if(stdGarName.getText().equals("  Gurdian name")){
            stdGarName.setText(null);
            stdGarName.requestFocus();
            mainPage.removePlaaceholderStytle(stdGarName);
        }
    }//GEN-LAST:event_stdGarNameFocusGained

    private void stdGarNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdGarNameFocusLost
        if(stdGarName.getText().length() == 0){
            MainPage.addPlaaceholderStytle(stdGarName);
            stdGarName.setText("  Gurdian name");
        }
    }//GEN-LAST:event_stdGarNameFocusLost

    private void stdGarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdGarNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdGarNameActionPerformed

    private void stdAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdAddressFocusGained
        if(stdAddress.getText().equals("  Address")){
            stdAddress.setText(null);
            stdAddress.requestFocus();
            mainPage.removePlaaceholderStytle(stdAddress);
        }
    }//GEN-LAST:event_stdAddressFocusGained

    private void stdAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdAddressFocusLost
        if(stdAddress.getText().length() == 0){
            MainPage.addPlaaceholderStytle(stdAddress);
            stdAddress.setText("  Address");
        }
    }//GEN-LAST:event_stdAddressFocusLost

    private void stdAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdAddressActionPerformed

    private void stdGarPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdGarPhoneFocusGained
        if(stdGarPhone.getText().equals("  Gurdian phone")){
            stdGarPhone.setText(null);
            stdGarPhone.requestFocus();
            mainPage.removePlaaceholderStytle(stdGarPhone);
        }
    }//GEN-LAST:event_stdGarPhoneFocusGained

    private void stdGarPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdGarPhoneFocusLost
        if(stdGarPhone.getText().length() == 0){
            MainPage.addPlaaceholderStytle(stdGarPhone);
            stdGarPhone.setText("  Gurdian phone");
        }
    }//GEN-LAST:event_stdGarPhoneFocusLost

    private void stdGarPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdGarPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdGarPhoneActionPerformed

    private void updateStdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStdBtnActionPerformed

        String studentName = stdName.getText();
        String studentIntake = stdIntake.getText();
        String studentPhone = stdPhone.getText();
        String studentBirthDate = (String)stdBirthDate.getSelectedItem();
        String studentBirthMonth = (String)stdBirthMonth.getSelectedItem();
        String studentBirthYear = (String)stdBirthYear.getSelectedItem();
        String studentGender = (String)stdGender.getSelectedItem();
        String studentSemester = (String)stdSem.getSelectedItem();
        String studentYear = (String)stdYear.getSelectedItem();
        String studentDepartment = (String)stdDept.getSelectedItem();
        String studentGurdianName = stdGarName.getText();
        String studentGurdianRelation = (String)stdRelGurd.getSelectedItem();
        String studentGurdianPhone = stdGarPhone.getText();
        String studentAddress = stdAddress.getText();
        String studentdBirthDay = studentBirthMonth + " " + studentBirthDate + ", " + studentBirthYear;

        if(!checkReadyForDatabese){
           if(studentName.equals("  Student name")){
                JOptionPane.showMessageDialog(rootPane, "Name is required");
            }else if(studentBirthDate.equals("day")){
                JOptionPane.showMessageDialog(rootPane, "Birth Date is required");
            }else if(studentBirthMonth.equals("month")){
                JOptionPane.showMessageDialog(rootPane, "Birth Month is required");
            }else if(studentBirthYear.equals("year")){
                JOptionPane.showMessageDialog(rootPane, "Birth Year is required");
            }else if(studentGender.equals("none")){
                JOptionPane.showMessageDialog(rootPane, "Gender is required");
            }else if(studentSemester.equals("none")){
                JOptionPane.showMessageDialog(rootPane, "Semester is required");
            }else if(studentYear.equals("year")){
                JOptionPane.showMessageDialog(rootPane, "Year is required");
            }else if(studentDepartment.equals("none")){
                JOptionPane.showMessageDialog(rootPane, "Department is required");
            }else if(studentIntake.equals("  Intake")){
                JOptionPane.showMessageDialog(rootPane, "Intake is required");
            }else if(studentPhone.equals("  Phone")){
                JOptionPane.showMessageDialog(rootPane, "Phone is required");
            }else if(studentGurdianName.equals("  Gurdian name")){
                JOptionPane.showMessageDialog(rootPane, "Guardian name is required");
            }else if(studentGurdianRelation.equals("none")){
                JOptionPane.showMessageDialog(rootPane, "Guardian Relation is required");
            }else if(studentGurdianPhone.equals("  Gurdian phone")){
                JOptionPane.showMessageDialog(rootPane, "Guardian phone is required");
            }else if(studentAddress.equals("  Address")){
                JOptionPane.showMessageDialog(rootPane, "Address is required");
            }else{
             try {
                String url = "jdbc:mysql://127.0.0.1/studentmangementsystem?serverTimezone=UTC";
                String user = "root";
                String password = "";

                Class.forName("com.mysql.cj.jdbc.Driver");
                connection = DriverManager.getConnection(url, user, password);

                // Prepare and execute the UPDATE statement
                String updateQuery = """
                UPDATE stdinfo
                SET stdName = ?,
                    stdIntake = ?,
                    stdPhone = ?,
                    stdBirth = ?,
                    stdGender = ?,
                    stdSemester = ?,
                    stdYear = ?,
                    stdDept = ?,
                    stdGar = ?,
                    stdGarRel = ?,
                    stdGarPhone = ?,
                    stdAddress = ?
                WHERE stdId = ?;"""; 

                PreparedStatement preparedStatement = connection.prepareStatement(updateQuery);
                preparedStatement.setString(1, studentName);
                preparedStatement.setString(2, studentIntake);
                preparedStatement.setString(3, studentPhone);
                preparedStatement.setString(4, studentdBirthDay);
                preparedStatement.setString(5, studentGender);
                preparedStatement.setString(6, studentSemester);
                preparedStatement.setString(7, studentYear);
                preparedStatement.setString(8, studentDepartment);
                preparedStatement.setString(9, studentGurdianName);
                preparedStatement.setString(10, studentGurdianRelation);
                preparedStatement.setString(11, studentGurdianPhone);
                preparedStatement.setString(12, studentAddress);
                preparedStatement.setString(13, searchStudentId); // Set stdId using the provided value

                preparedStatement.executeUpdate();
                updateComplete = true;
            } catch (SQLException ex) {
                updateComplete = false;
                Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(UpdateStudent.class.getName()).log(Level.SEVERE, null, ex);
            }

            }
        }

        if(updateComplete){
            JOptionPane.showMessageDialog(rootPane, "Upadate Sucessfully");

           
            addStudent.removeText(stdName);
            addStudent.removeText(stdIntake);
            addStudent.removeText(stdPhone);
            addStudent.removeText(stdGarName);
            addStudent.removeText(stdGarPhone);
            addStudent.removeText(stdAddress);
            stdName.setText("  Student name");
            stdIntake.setText("  Email");
            stdPhone.setText("  Phone");
            stdGarName.setText("  Gurdian name");
            stdGarPhone.setText("  Gurdian phone");
            stdAddress.setText("  Address");
            stdDept.setSelectedItem("none");
            stdSem.setSelectedItem("none");
            stdBirthMonth.setSelectedItem("month");
            stdBirthDate.setSelectedItem("day");
            stdBirthYear.setSelectedItem("year");
            stdDept.setSelectedItem("noe");
            stdYear.setSelectedItem("year");
            stdGender.setSelectedItem("none");
            stdRelGurd.setSelectedItem("none");
            updateComplete = false;
        }
    }//GEN-LAST:event_updateStdBtnActionPerformed

    private void stdNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdNameFocusGained
        if(stdName.getText().equals("  Student name")){
            stdName.setText(null);
            stdName.requestFocus();
            mainPage.removePlaaceholderStytle(stdName);
        }
    }//GEN-LAST:event_stdNameFocusGained

    private void stdNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdNameFocusLost
        // TODO add your handling code here:
        if(stdName.getText().length() == 0){
            MainPage.addPlaaceholderStytle(stdName);
            stdName.setText("  Student name");
        }
    }//GEN-LAST:event_stdNameFocusLost

    private void stdNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdNameActionPerformed

    }//GEN-LAST:event_stdNameActionPerformed

    private void stdIntakeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdIntakeFocusGained
        if(stdIntake.getText().equals("  Intake")){
            stdIntake.setText(null);
            stdIntake.requestFocus();
            mainPage.removePlaaceholderStytle(stdIntake);
        }
    }//GEN-LAST:event_stdIntakeFocusGained

    private void stdIntakeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdIntakeFocusLost
        if(stdIntake.getText().length() == 0){
            MainPage.addPlaaceholderStytle(stdIntake);
            stdIntake.setText("  Intake");
        }
    }//GEN-LAST:event_stdIntakeFocusLost

    private void stdIntakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdIntakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdIntakeActionPerformed

    private void stdPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdPhoneFocusGained
        if(stdPhone.getText().equals("  Phone")){
            stdPhone.setText(null);
            stdPhone.requestFocus();
            mainPage.removePlaaceholderStytle(stdPhone);
        }
    }//GEN-LAST:event_stdPhoneFocusGained

    private void stdPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stdPhoneFocusLost
        if(stdPhone.getText().length() == 0){
            MainPage.addPlaaceholderStytle(stdPhone);
            stdPhone.setText("  Phone");
        }
    }//GEN-LAST:event_stdPhoneFocusLost

    private void stdPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdPhoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBtnFromDelete;
    private javax.swing.JLabel deleteStudentText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logOutBtn1;
    private javax.swing.JTextField searchStdId;
    private javax.swing.JLabel searchStudent;
    private javax.swing.JPanel searchStudentBtn;
    private javax.swing.JTextField stdAddress;
    private javax.swing.JComboBox<String> stdBirthDate;
    private javax.swing.JComboBox<String> stdBirthMonth;
    private javax.swing.JComboBox<String> stdBirthYear;
    private javax.swing.JComboBox<String> stdDept;
    private javax.swing.JTextField stdGarName;
    private javax.swing.JTextField stdGarPhone;
    private javax.swing.JComboBox<String> stdGender;
    private javax.swing.JTextField stdIntake;
    private javax.swing.JTextField stdName;
    private javax.swing.JTextField stdPhone;
    private javax.swing.JComboBox<String> stdRelGurd;
    private javax.swing.JComboBox<String> stdSem;
    private javax.swing.JComboBox<String> stdYear;
    private javax.swing.JButton updateStdBtn;
    // End of variables declaration//GEN-END:variables
}
